@host = http://127.0.0.1:8000
@email = http-test-user@example.com
@password = qwer1234

### 로그인
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
