@host = http://127.0.0.1:8000
@accessToken =

### 선택한 관심사 목록 조회
GET {{host}}/api/interest-targets
Authorization: Bearer {{accessToken}}

### 관심사 선택 동기화
PUT {{host}}/api/interest-targets
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "interestIds": ["interest_1", "interest_2"]
}
