@host = http://127.0.0.1:8000
@accessToken =

### 웹 검색
GET {{host}}/api/web-search?query=테스트&count=5
Authorization: Bearer {{accessToken}}

### 웹 검색 - 최근 1개월
GET {{host}}/api/web-search?query=테스트&count=5&freshness=month
Authorization: Bearer {{accessToken}}

### 웹 검색 - 인증 누락
GET {{host}}/api/web-search?query=테스트&count=5
