from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD"
    AUTH_REQUIRED_AGREEMENT_MISSING = "AUTH_REQUIRED_AGREEMENT_MISSING"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"
    AUTH_REFRESH_TOKEN_COOKIE_MISSING = "AUTH_REFRESH_TOKEN_COOKIE_MISSING"
    AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN"
    AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INTEREST_TARGET_INVALID_TYPE = "INTEREST_TARGET_INVALID_TYPE"
    INTEREST_TARGET_ALREADY_EXISTS = "INTEREST_TARGET_ALREADY_EXISTS"
    INTEREST_TARGET_NOT_FOUND = "INTEREST_TARGET_NOT_FOUND"
